default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: storage/development.sqlite3

test:
  <<: *default
  database: storage/test_postgresql

production:
  encoding: unicode
  url: <%= ENV['DATABASE_URL'] %>
  pool: 5
